### ISSUE TITLE
MeshDecomposition  case

### ISSUE THREAD

**Issue by alexhackbai** [gradientspace/geometry3Sharp#12]
i want one mesh separated into multiple mesh？thank

**Comment by rms80** [comment]
Do you want to separate by connected components? IE like you have 3 spheres in one DMesh, and you  want to break it down into a separate DMesh for each sphere? Then you can use MeshConnectedComponents class, which can group by connected triangles or vertices.

MeshDecomposition is for splitting a mesh into chunks of maximum size, the defaults split into chunks < 64k verts/tris, so that each chunk will fit into a Unity Mesh object. However it completely ignores the structure of the mesh.

**Comment by alexhackbai** [comment]
Can you give me an example?

**Comment by rms80** [comment]
DMesh3[] componentMeshes = MeshConnectedComponents.Separate(inputMesh);
