### ISSUE TITLE
Is Surface Simplification Using Quadric Error Metrics not actually what it is?

### ISSUE THREAD

**Issue by saltukkos** [gradientspace/geometry3Sharp#49]
I read [original article](https://www.ri.cmu.edu/pub_files/pub2/garland_michael_1997_1/garland_michael_1997_1.pdf) and explored code in Reducer.cs, and found that while collecting initial "fundamental error quadric" you are multiply it by area of triangle https://github.com/gradientspace/geometry3Sharp/blob/0c84997f47de4e2f4d875dea63164cf22ba912a5/mesh/Reducer.cs#L243
Why do you doing this? In paragraph 5 of original article error metric is calculated as 
> summ_p(K_p)

without any respect to the area of defining triangle, can you please explain this? Does this change the optimal point for contraction?

**Comment by rms80** [comment]
https://mgarland.org/files/papers/quadric2.pdf

the first paper is rarely the best one. yes, any weighting affects the optimal point.

**Comment by saltukkos** [comment]
I read article you sent.
OK, I found "it is useful to weight quadrics by the area of the contributing triangle". It seems to work, but maybe we need to consider this weights in some other places when reducing? Because now I got different results on one mesh with different scales (when reduce to triangles count).
For example, look at the ear
![image](https://user-images.githubusercontent.com/13440397/39035446-3bab704e-44a4-11e8-9dd3-887e09ad1a98.png) 
![image](https://user-images.githubusercontent.com/13440397/39035690-25e87cb0-44a5-11e8-943e-57c99a9e2dd1.png)
and it's a bit strange, because areas of triangles should rise proportionally.

The results will be the same if I delete multiplying on "w" in Add method

**Comment by rms80** [comment]
because it is based on sequential edge collapses, the final result can be wildly different if even one edge is collapsed in a different order. The code is in floating point, so individual quadrics that evaluate to nearly identical error can easily switch order if you change the vertices even a tiny bit (eg by scaling). This is particularly an issue in planar regions, and also on near-regular meshes where all the initial one-rings are nearly identical.

Also, the OptimalPoint() function has a hardcoded epsilon to avoid singular matrices, in such cases basic midpoint interpolation is used. This actually happens quite often. As you scale down the shape, it will happen more often, and each time it does, it will have a downstream effect on the output mesh.

It's possible that SVD could be used to deal with these singular matrices and make the results more consistent. It is probably infrequent enough that it wouldn't be a huge computational cost. 

If you want to minimize floating point effects, you probably should also scale to/from a unit box before running the algorithm. This actually does make a difference, as floats/doubles are 'denser' closer to 0.

**Comment by saltukkos** [comment]
Okay, thanks a lot!
By the way, is there any built-in way to minimize vertex numbers (I mean indices) after mesh reducing for more effective storing in memory?

**Comment by tsokomani** [comment]
Is there any source code for C#?

**Comment by justinmeiners** [comment]
Leaving a comment so I can find this later.
